[package]
name = "local-shock-tracking"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.14.5"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
