[package]
name = "local-shock-tracking"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
faer = "0.21.9"
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
